@startmindmap

<style>
mindmapDiagram {
  node {
    MaximumWidth 200
    BackgroundColor lightgrey
  }
   .blue {
      BackgroundColor lightBlue
   }
   .rose {
       BackgroundColor #FFBBCC
   }
   .yellow {
       BackgroundColor lightyellow
   }
}
</style>

* Безопасность данных <<rose>>
** Публичные <<grey>>
*** Витрина жилья <<yellow>>
**** Искажение данных <<rose>>
***** Значительный <<blue>>
****** Вводит клиентов в заблуждение и портит имидж.
**** Потеря данных <<rose>>
***** Незначительный <<blue>>
****** Данные можно восстановить.
*** Маркетинговые материалы<<yellow>>
**** Искажение данных <<rose>>
***** Значительный <<blue>>
****** Портит имидж компании.

** Внутренние <<grey>>
*** BI-отчёты <<yellow>>
**** Утечка данных <<rose>>
***** Значительный <<blue>>
****** Предоставит конкурентам информацию о стратегических показателях и планах компании.
**** Искажение данных <<rose>>
***** Значительный <<blue>>
****** Может привести к ошибочным управленческим решениям и убыткам.
**** Некачественные данные <<rose>>
***** Значительный <<blue>>
****** Затрудняют анализ и снижают точность прогнозов.
*** Технические данные (документация, логи, информация о сетевой инфраструктуре) <<yellow>>
**** Утечка данных <<rose>>
***** Значительный <<blue>>
****** Упростит подготовку и проведение атак на систему.
**** Искажение данных <<rose>>
***** Значительный <<blue>>
****** Может вызвать ошибки в эксплуатации и развитии сервисов.


** Конфиденциальные <<grey>>
*** Данные клиентов/собственников (ФИО, телефон, email) <<yellow>>
**** Утечка данных <<rose>>
***** Критический <<blue>>
****** Нарушение 152‑ФЗ, штрафы и репутационные потери.
**** Потеря данных <<rose>>
***** Критический <<blue>>
****** Делает невозможным контакт с клиентами и завершение сделок.
**** Искажение данных <<rose>>
***** Критический <<blue>>
****** Приводит к ошибкам в договорах и претензиям клиентов.
**** Некачественные данные <<rose>>
***** Значительный <<blue>>
****** Затрудняют связь с клиентами и ухудшают качество обслуживания.
**** Обесценивание данных <<rose>>
***** Незначительный <<blue>>
****** Со временем контакты устаревают, если не обновлять их актуальность.

*** Данные сделок <<yellow>>
**** Утечка данных <<rose>>
***** Критический <<blue>>
****** Раскрывает конфиденциальную информацию о клиентах и бизнесе.
**** Искажение данных <<rose>>
***** Критический <<blue>>
****** Приводит к неверным договорам и финансовым убыткам.
**** Потеря данных <<rose>>
***** Критический <<blue>>
****** Делает невозможным их завершение или подтверждение сделок.

*** Платёжные данные собственников <<yellow>>
**** Утечка данных <<rose>>
***** Критический <<blue>>
****** Даёт злоумышленникам возможность кражи средств или мошенничества.
**** Искажение данных <<rose>>
***** Критический <<blue>>
****** Приводят к ошибочным начислениям и финансовым спорам.
*** Учётные данные клиентов/собственников (логин, пароль, токены) <<yellow>>
**** Утечка данных <<rose>>
***** Критический <<blue>>
****** Позволяет злоумышленникам получить доступ к аккаунтам пользователей.
**** Потеря данных <<rose>>
***** Значительный <<blue>>
****** Приводит к невозможности клиентов войти в систему и использовать сервисы.
**** Искажение данных <<rose>>
***** Значительный <<blue>>
****** Блокируют доступ клиентов к своим данным.

** Секретные <<grey>>
*** Доступы к БД <<yellow>>
**** Утечка данных <<rose>>
***** Критический <<blue>>
****** Данных БД даёт злоумышленникам полный доступ ко всем хранимым данным.
**** Потеря данных <<rose>>
***** Критический <<blue>>
****** Делает невозможным управление базами и восстановление данных.
*** API-токены партнёров <<yellow>>
**** Утечка данных <<rose>>
***** Критический <<blue>>
****** Открывает третьим лицам доступ к внутренним сервисам и данным компании.
*** Учётные данные администраторов <<yellow>>
**** Утечка данных <<rose>>
***** Критический <<blue>>
****** Позволяет захватить контроль над всей ИТ-инфраструктурой компании.
**** Искажение данных <<rose>>
***** Критический <<blue>>
****** Могут вызвать сбои и парализовать работу систем.

@endmindmap
